
const Discord = require('discord.js');
const Twana1 = new Discord.Client();
const Twana2 = new Discord.Client();
const Twana3 = new Discord.Client();
const Twana4 = new Discord.Client();
const Twana5 = new Discord.Client();
const Twana6 = new Discord.Client();
const Twana7 = new Discord.Client();
const Twana8 = new Discord.Client();
const Twana9 = new Discord.Client();
const Twana10 = new Discord.Client();
const Twana11 = new Discord.Client();
const Twana12 = new Discord.Client();
const Twana13 = new Discord.Client();
const Twana14 = new Discord.Client();
const Twana15 = new Discord.Client();
const Twana16 = new Discord.Client();
const Twana17 = new Discord.Client();
const Twana18 = new Discord.Client();
const Twana19 = new Discord.Client();
const Twana20 = new Discord.Client();
const Twana21 = new Discord.Client();
const Twana22 = new Discord.Client();
const Twana23 = new Discord.Client();
const Twana24 = new Discord.Client();
const Twana25 = new Discord.Client();
const Twana26 = new Discord.Client();
const Twana27 = new Discord.Client();
const Twana28 = new Discord.Client();
const Twana29 = new Discord.Client();
const Twana30 = new Discord.Client();
const Twana31 = new Discord.Client();
const Twana32 = new Discord.Client();
const Twana33 = new Discord.Client();
const Twana34 = new Discord.Client();
const Twana35 = new Discord.Client();
const Twana36 = new Discord.Client();
const Twana37 = new Discord.Client();
const Twana38 = new Discord.Client();
const Twana39 = new Discord.Client();
const Twana40 = new Discord.Client();
const Twana41 = new Discord.Client();
const Twana42 = new Discord.Client();
const Twana43 = new Discord.Client();
const Twana44 = new Discord.Client();
const Twana45 = new Discord.Client();
const Twana46 = new Discord.Client();
const Twana47 = new Discord.Client();
const Twana48 = new Discord.Client();
const Twana49 = new Discord.Client();
const Twana50 = new Discord.Client();
const Twana51 = new Discord.Client();
const Twana52 = new Discord.Client();
const Twana53 = new Discord.Client();
const Twana54 = new Discord.Client();
const Twana55 = new Discord.Client();
const Twana56 = new Discord.Client();
const Twana57 = new Discord.Client();
const Twana58 = new Discord.Client();
const Twana59 = new Discord.Client();
const Twana60 = new Discord.Client();
const Twana61 = new Discord.Client();
const Twana62 = new Discord.Client();
const Twana63 = new Discord.Client();
const Twana64 = new Discord.Client();
const Twana65 = new Discord.Client();
const Twana66 = new Discord.Client();
const Twana67 = new Discord.Client();
const Twana68 = new Discord.Client();
const Twana69 = new Discord.Client();
const Twana70 = new Discord.Client();
const Twana71 = new Discord.Client();
const Twana72 = new Discord.Client();
const Twana73 = new Discord.Client();
const Twana74 = new Discord.Client();
const Twana75 = new Discord.Client();
const Twana76 = new Discord.Client();
const Twana77 = new Discord.Client();
const Twana78 = new Discord.Client();
const Twana79 = new Discord.Client();
const Twana80 = new Discord.Client();
const Twana81 = new Discord.Client();
const Twana82 = new Discord.Client();
const Twana83 = new Discord.Client();
const Twana84 = new Discord.Client();
const Twana85 = new Discord.Client();
const Twana86 = new Discord.Client();
const Twana87 = new Discord.Client();
const Twana88 = new Discord.Client();
const Twana89 = new Discord.Client();
const Twana90 = new Discord.Client();
const Twana91 = new Discord.Client();
const Twana92 = new Discord.Client();
const Twana93 = new Discord.Client();
const Twana94 = new Discord.Client();
const Twana95 = new Discord.Client();
const Twana96 = new Discord.Client();
const Twana97 = new Discord.Client();
const Twana98 = new Discord.Client();
const Twana99 = new Discord.Client();
const Twana100= new Discord.Client();



Twana1.login("ODEzMTIwMTk2Nzg5MjcyNTk4.YDKw4A.rmu27KybDgm0SFdEyGfW274kh14");
Twana2.login("ODEzMTI2NTMwMzM0NTg4OTU4.YDK1og.jWGR8iCXsKFCPnumdfExjfp0z2c");
Twana3.login("ODEzMzU0ODYyMDc5MTE1MjY1.YDOHdg.ST2kVvsMoc-zeod5lnbSkyreLiQ");
Twana4.login("ODEzMzU2OTI5NjQ0MTAxNjUz.YDOV9w.c2tWB3TnocRQ77_EGEZKE6o-0Ps");
Twana5.login("ODEzMzU2OTI5NjQ0MTAxNjUz.YDOV9w.c2tWB3TnocRQ77_EGEZKE6o-0Ps");
Twana6.login("ODEzMzU4ODA2ODcxNDQxNDYx.YDOXcA.UgtGfExYZDXvlABAHy5d9QNTRjc");
Twana7.login("ODEzNDEwMjI1MDg3NTc4MTEy.YDO50w.SvVS73kmErqzuhG0P_h6qC75uN8");
Twana8.login("ODEzNDExNTQ0MjY3MjI3MTM2.YDO7Pw.g6pGf-2LGArDJK6jxc1SJeUrimU");
Twana9.login("ODEzNDEyODg2MDg5MDM5ODkz.YDO8IQ.nQUGuWK-_RqOl2eut6IVoEs-zo8");
Twana10.login("ODEwMTk3MTI0NzA3OTA5NjQy.YCruhQ.VyUFg69tjhAUpd1eX0kt3nVBFNE");
Twana11.login("ODEwOTk0NDk1MDY3NTIxMDM1.YCvkfw.XEXUH9XlQ99oCfGF4cnXGpUes6M");
Twana12.login("ODExMjU4NTAxNDkzMDMwOTYy.YCvmCA.87Gmly6lg6Qp1uhrZT8NvQnAsfw");
Twana13.login("ODEyNDExOTU4Njk1Mjk3MDI1.YDDdOw.5W9dmNXgW7BBpPNT95Ya-FMi_yE");
Twana14.login("ODA5NTI2Njc1MDUwMjAxMTQw.YDEb7A.wjDRHnKhygJv5vQZXXk7ik-7HOs");
Twana15.login("ODEyNzI2NjE4NzIzNzEzMDU1.YDE97g.CptaEnE2e1A0141Rx5FnGnVoprs");
Twana16.login("ODEyNjk4MTMzMDkxNzEzMDM1.YDFkDQ.Fim6T61WlwQfkt3122N1AWNbMSo");
Twana17.login("ODEyNjk4MTMzMDkxNzEzMDM1.YDJ4aA.UeWoOauIs-srVeIcnGqDUKwGY0w");
Twana18.login("ODEyNjk4MTMzMDkxNzEzMDM1.YDJ4aA.UeWoOauIs-srVeIcnGqDUKwGY0w");
Twana19.login("ODEzMDY3NTU3MTc4NzAzOTQz.YDJ6pA.NM6XgK9-zGdw0VgNwNKGKglcO_4");
Twana20.login("ODEzMDc2MTgxMTI0OTA3MDc4.YDKkZg.iR8dz0f7tUTJUtpHEEDHlXWHHkw");
Twana21.login("ODA4MDEwODEyMzU0NTkyNzk5.YCEgAg.Q-_ZsgpbIB8QrSae-5xsU76Q-Ng");
Twana22.login("ODA4Mjk4MjgyMjQ1Njg1MjYw.YCEheA.mtKy-UAt_0HTq4rcstCeQ1JXs_Q");
Twana23.login("ODA4Mjk5NzY0ODE4NTA5ODU2.YCEi4Q.2zG_fulrDaGq5e1Pv0OVMqadzZ8");
Twana24.login("ODA4MzAxMjc0ODcyNjc2NDE0.YCEkDg.hqPxVuafgfRKm8XpdmshccFpibA");
Twana25.login("ODA4MzAyNzQ0MjUwNjEzNzgx.YCElhw.uMNtUeER51-fT5a-li11qPrcQuc");
Twana26.login("ODA4MzAzOTc4Nzk4MjUyMDYz.YCF7RQ.XLiWXmV5iqzVBduGaikbPcFenPA");
Twana27.login("Nzk4ODgwMzI5ODcxNjU0OTMz.YCGCtw.NQjFQUA0v5XBnTZ4cedb2WLVRY4");
Twana28.login("ODAxNDEzNzg1OTA2MDUzMTgx.YCGD_A.I0IqBmlf3ieJdMs7TKR92lMkALQ");
Twana29.login("Nzk4ODg2NzM4NzUwODY1NDI5.YCGFYw.V9TwqJlEIIPF3c6mA-7FHfnNyxc");
Twana30.login("Nzk4OTI0NjEzNDg4ODY5NDU3.YCGGKw.9pVAehavVQbLmq6UHkyaHvfTODY");
Twana31.login("ODA4Mzk2MzgxODk0NzM3OTQw.YCGhXg.a0ogCoPbUOJYAGmHs0yZH2SEQkY");
Twana32.login("ODA3NzE1MDM4ODE4ODYxMTI3.YCK9GA.i810awsW8GjBQS32TGFqbe48dpE");
Twana33.login("ODA4ODEzMTY4MDExOTAyOTg2.YCOhDQ.v49MGhEHYF5g2Jilxebp6lHz5jo");
Twana34.login("ODA4OTg2NTE2NzQyOTk1OTY4.YCOkzg.TWgFeKptlfTZ2nkn9RV8Jk41OlU");
Twana35.login("ODA4OTkxMDk0NDc4MDc4MDEy.YCOnLA.7RtBQXZjyJtAC4uTyx6Z6KrI9vA");
Twana36.login("ODA4OTkyNjYyMjkxMDg3Mzcw.YCOocQ.xHA9jqNAmD5712alPygjB-YiNf0");
Twana37.login("ODA4OTk0NDMzNzM1MDY1NjI3.YCOpng.kIbJkaiX52xbewN1mygMaGYcPd4");
Twana38.login("ODA4OTk3Nzg0MDU2NDk2MTU4.YCOsrw.I5gFDQwrSazDaAwORKV3KkAVuts");
Twana39.login("ODA4OTk4OTU4NDcwOTIyMjUx.YCOt5g.VmOL9-lhZ3H458PTaMf50zSo8HQ");
Twana40.login("ODAyNjM1NDQ2NzAyMTc4MzA3.YAyIKQ.HoVBcg7en_PURjtplc33ZRh8B8Y");
Twana41.login("ODAyNjM3ODMzODY4NTQxOTcy.YAyLAA.HPtRZexQDKH1cLG3Rm61o2qCLxk");
Twana42.login("ODAyNjQwNjY5MzU2NTg5MDg2.YAyM5Q.8avk1zsidzhcohWFprcBx7HLh3Q");
Twana43.login("ODAyNjYxODE1MTI5MjEwOTQx.YAygWQ.bVc54PwVdNoedmnAtizV5I_b438");
Twana44.login("ODAyNjcyMzA2NzgyMzM5MTMy.YAyrkQ.ynyjSn9wr58_T6ORXe8Uhxax4ng");
Twana45.login("ODAyNjc1NzYyMDExNTcwMjA3.YA0_4Q.KChi1P-v3cSc5Ps9IiMZ7LptOac");
Twana46.login("ODA5NDkwMzA5MzE0Mzc5ODY4.YCWNgw.hvDOt__nd5Kz60gcGn9WsT5E6YU");
Twana47.login("ODA5NTE5NDA3MDM3OTM5NzUy.YCWS3w.NJGLa2FO35tHfASlXNcAI-dL9KE");
Twana48.login("ODA5NTIwOTkyMTQ0NTg4ODIw.YCWUww.9q1zZj8wrgoBs9rH7eSQGFWLYvo");
Twana49.login("ODA5NTI1MjE2MTU2ODQ0MTAy.YCWYLg.017jF6PvRdDgVVp5XV-Tt9eTlDk");
Twana50.login("ODEzNTAyOTM5NzU4NDYwOTY4.YDQQAw.tQ8ROW2huNNSREvzrDlmvfGdMpY");
Twana51.login("NzkzMjM3NjU5NDA4NjYyNTk4.X-sGsw.QKJ612Vv_8BlNgWu-JJlufw18PA");
Twana52.login("NzkzMjM3MDA1NzIyMDU4ODEy.X-r7dw.1GRVoVTc58f4PX4tDtOBqF4fYuA");
Twana53.login("NzkzMjM2NDc3NTM4MzM2ODA5.X-qdcw.TXPtu8j5a7IeRXa6nSajSXvSdqU");
Twana54.login("NzkzMjM1ODg2ODg3Nzk2ODA4.X-qdUA.iZgq9TrYEyi-xft_3K8jPJemHt4");
Twana55.login("NzkzMjM1MzIxNjkyNDg3NzEw.X-qdJA.u9Ljz3qBz_MzwwIVpjLoga5Ded8");
Twana56.login("NzkzMjM0NjYzNTMwNDMwNTA1.X-qc9g.MIINVTVVft3B9pNgx8dJu0qCjO4");
Twana57.login("NzkzMjM0MDgwOTc5MjIyNTY5.X-qc0A.l165r5SLJuEnJi6P6HCxGoVKKl0");
Twana58.login("NzkzMjMzNDk0OTAxMTI5Mjc2.X-qcnA.rCsSxdaDTq5hmmyI9sqpIFln6JM");
Twana59.login("NzkzMjMyOTAyODQ5ODIyNzMx.X-qccg.bhtp8JmblgnyGgdnvZVsZKMfqjo");
Twana60.login("NzkzMjMyMzczMDg0NDU0OTMz.X-qcJw.hfRqEJi4JqvqXMiXfbC5l-UyW7so");
Twana61.login("NzkzMjE2MDY2MDI4NTY4NjM2.X-qb-A.Ci5vA6ehnH_q1WejeFVQO033ORA");
Twana62.login("NzkzMjMxMTQwODY1MzEwNzMw.X-qb0A.bGIAbTwLFjSq6CWocQWXxORGLbk");
Twana63.login("NzkzMjMwNDgyNTEwMDUzMzc3.X-qY3g.O-0wPyHxFQnfQOjCATOs_26r0oo");
Twana64.login("NzkzMjI5OTM2OTQwNjc5MjE4.X-qYkg.n0kXD4iS_0JWhBxFL1VQmzozA3w");
Twana65.login("NzkzMjI5MjQ1MjY5NjcxOTU2.X-qYYQ.Daakzn3_z0i_D3U4NrHG8dv0SPY");
Twana66.login("NzkzMjI4NjcyNjI2NzIwODI5.X-qYOA.4TZExeJhjeTHVAjF2ZMwsQl4apM");
Twana67.login("NzkzMjI4MDkwMzQ3MjI1MTE5.X-qX5w.LuY1v4h2goIbmoHoeOg4N11e3Jk");
Twana68.login("NzkzMjI3NDU0MTYwMzA2MTk2.X-qWEw.fHSAaUQmG_wzdXZ_q9HMUgZGras");
Twana69.login("NzkzMjI2OTMzNTMzODAyNTU3.X-qV8A.saTAa03wocPkUWl6T_XT4_DQC9Y");
Twana70.login("NzkzMjI2MzIzMTY2MzYzNjY4.X-qVwg.Zj269RPOv1MuCSk2UofwZDjGQxQ");
Twana71.login("NzkzMjI1NzA2MDk1NTA5NTU0.X-qVlQ.BjaDPUXcEBQyNpiNEDu8636w-NQ");
Twana72.login("NzkzMjI1MTUzMjYxMDc2NTAx.X-qVZw.bqpa2FApAtyQtWlLSo0OhzZHIq8");
Twana73.login("NzkzMjI0NjMxOTIxODAzMzY2.X-qU4Q.A0JO8j-oW-_JSc1CZs7ohTIiVyw");
Twana74.login("NzkzMjI0MDY5MzMxMDI1OTQw.X-qUqQ.8_MuCBTYTancl5sIvPR025cNZqw");
Twana75.login("NzkzMjIzNTMyMTAzMzM2MDE3.X-qUag.YVFhylIoF0YRoh6caW1VFEGYIyE");
Twana76.login("NzkzMjIyNTIyMzEyOTgyNTM4.X-qUEg.Zh2YVVs45K8pDIlFG5ZcvtPVqes");
Twana77.login("NzkzMjIxMDYzODY0NDgzODkw.X-qTwg.2wFMHjNQgzhQt9wDSFPhxRfhiU0");
Twana78.login("NzkzMjIwMjkzNjgxMjE3NTU3.X-qTaA.XHj3G1w7gzW_mP_fhsXqRs2OgI4");
Twana79.login("NzkzMjE5MTQxMzQ2Nzg3NDIw.X-qTIQ.qi-80n42nIDDaPnC1FSj6bzylrs");
Twana80.login("NzkzMjE3MzUxOTIzMTM4NjMw.X-qSmQ.IyS1FE7QdSR2Qzb4BtjF1MAHa3M");
Twana81.login("NzkzMjE3MDAwMDY3MTcwNDA1.X-qSGw.WuP-T1Sr8rJR8lYi8wPaRll2Ywg");
Twana82.login("NzkzMjE1MzUyMjI1Mzk4ODA1.X-qREQ.3lVTLL7yxJG7WB-kAmafZmVvW5g");
Twana83.login("");
Twana84.login("");
Twana85.login("");
Twana86.login("");
Twana87.login("");
Twana88.login("");
Twana89.login("");
Twana90.login("");
Twana91.login("");
Twana92.login("");
Twana94.login("");
Twana95.login("");
Twana96.login("");
Twana97.login("");
Twana98.login("");
Twana99.login("");
Twana100.login("");









